version: 0.0
os: ubuntu

files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
